[package]
name = "randomforest"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
edition = "2018"
description = "Random forest regressor and classifier"
homepage = "https://github.com/sile/randomforest"
repository = "https://github.com/sile/randomforest"
readme = "README.md"
categories = ["science"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
coveralls = {repository = "sile/randomforest"}

[dependencies]
ordered-float = "2"
rand = "0.7"
rayon = "1"
serde = { version = "1", features = ["derive"], optional = true }
thiserror = "1"

[dev-dependencies]
anyhow = "1"
